# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            fiona
tagline:          '从这里出初江湖，携手仗剑江湖路'
description:      'Hello'
baseurl:              /blog
author:
  name:           'fiona'
  url:            https://github.com/fiona23

paginate:        2
paginate_path:   "blog/bloglist/page:num"

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : fiona
