# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            fiona
tagline:          'Time is limited, To be a better man'
description:      'Hello,World! Here is my personal weblog about technology and life.'
url:              http://fiona23.github.io/blog/
author:
  name:           'fiona'
  url:            https://github.com/fiona23

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : fiona
